<center style="
    border-radius:4px;
    border: 1px solid #cfd7e6;
    box-shadow: 0 1px 3px 0 rgba(89,105,129,.05), 0 1px 1px 0 rgba(0,0,0,.025);
    padding: 1em;"
    >

@startuml
    actor "Користувач" as User
    
    usecase "<b>UserLogin<b> \n Вхід в систему" as UC_1
    usecase "<b>UserExit<b> \n Вихід з системи" as UC_2
    usecase "<b>UserEditSuggestions<b> \n Пропозиція оновити дані " as UC_3
    usecase "<b>UserUploadSuggestion<b> \n Пропозиція завантажити \n нові дані " as UC_4
    usecase "<b>VisualizeData<b> \n Візуалізація даних" as UC_5
    usecase "<b>UserAuth<b> \n Авторизація користувача" as UC_6
    usecase "<b>UserDataSuggestion<b> \n Пропозиції користувача \n щодо змін в даних" as UC_7
    usecase "<b>RateData<b> \n Оцінка даних користувачем" as UC_8

    UC_1 .u.> UC_6:extends
    UC_2 .d.> UC_6:extends
    
    UC_3 .u.> UC_7:extends
    UC_4 .d.> UC_7:extends
    
    User -d-> UC_8
    User -l-> UC_7
    User -r-> UC_6
    User -u-> UC_5

@enduml

</center>