<center style="
    border-radius:4px;
    border: 1px solid #cfd7e6;
    box-shadow: 0 1px 3px 0 rgba(89,105,129,.05), 0 1px 1px 0 rgba(0,0,0,.025);
    padding: 1em;"
    >


@startuml
    actor "Адміністратор" as Admin
    
    usecase "<b>AdminLogin<b> \n Вхід адміністратора \n в систему" as UC_1
    usecase "<b>AdminExit<b> \n Вихід адміністратора \n з системи" as UC_2
    usecase "<b>AdminUpload<b> \n Завантаження даних \n в систему" as UC_3
    usecase "<b>AdminDelete<b> \n Видалення даних \n з системи " as UC_4
    usecase "<b>AdminEdit<b> \n Оновлення даних в системі " as UC_5
    usecase "<b>AdminConfirmChange<b> \n Підтвердження змін у даних" as UC_6
    usecase "<b>AdminConfirmUpload<b> \n Підтвердження додавання /n нових даних" as UC_7
    usecase "<b>AdminBan<b> \n Блокування користувача" as UC_8
    usecase "<b>AdminAuth<b> \n Авторизація адміністратора" as UC_A
    usecase "<b>AdminDataManagment<b> \n Управління даними в системі" as UC_M
    usecase "<b>AdminDataInteraction<b> \n Взаємодія з даними в системі" as UC_I
    
    Admin -l-> UC_A
    Admin -r-> UC_M
    Admin -d-> UC_8
    
    UC_1 .u.> UC_A:extends
    UC_2 .d.> UC_A:extends
    
    UC_I .l.> UC_M:extends
    
    UC_3 .u.> UC_I:extends
    UC_4 .l.> UC_I:extends
    UC_5 .d.> UC_I:extends
    
    UC_6 .u.> UC_M:extends
    UC_7 .d.> UC_M:extends

@enduml

</center>