<center style="
    border-radius:4px;
    border: 1px solid #cfd7e6;
    box-shadow: 0 1px 3px 0 rgba(89,105,129,.05), 0 1px 1px 0 rgba(0,0,0,.025);
    padding: 1em;"
    >

@startuml


entity User <<ENTITY>> #fe500a 
entity User.id <<NUMBER>> #ffe396
entity User.first_name <<TEXT>> #ffe396
entity User.last_name <<TEXT>> #ffe396
entity User.login <<TEXT>> #ffe396
entity User.email <<TEXT>> #ffe396
entity User.password <<TEXT>> #ffe396
User.id --* User
User.login -l-* User
User.email --* User
User.password --* User
User.first_name -r-* User
User.last_name --* User

entity Role <<ENTITY>> #fe500a
entity Role.id <<NUMBER>> #ffe396
entity Role.alias <<TEXT>> #ffe396
Role.id -d-* Role
Role.alias -d-* Role

entity Permission_Role <<ENTITY>> #fe500a

entity Permission <<ENTITY>> #fe500a
entity Permission.id <<NUMBER>> #ffe396
entity Permission.alias <<TEXT>> #ffe396
Permission.id -l-* Permission
Permission.alias -r-* Permission

entity Access <<ENTITY>> #fe500a
entity Access.id <<NUMBER>> #ffe396
Access.id --* Access

entity Dataset <<ENTITY>> #fe500a
entity Dataset.id <<NUMBER>> #ffe396
entity Dataset.title <<TEXT>> #ffe396
entity Dataset.description <<TEXT>> #ffe396  
entity Dataset.rating <<TEXT>> #ffe396
Dataset.id -u-* Dataset
Dataset.title -u-* Dataset
Dataset.description -u-* Dataset
Dataset.rating -l-* Dataset


entity Datafile <<ENTITY>> #fe500a
entity Datafile.id <<NUMBER>> #ffe396
entity Datafile.guid <<NUMBER>> #ffe396
entity Datafile.title <<TEXT>> #ffe396
entity Datafile.memo <<TEXT>> #ffe396
entity Datafile.size <<NUMBER>> #ffe396
entity Datafile.uploadedAt <<DATETIME>> #ffe396
Datafile.id -r-* Datafile
Datafile.guid -u-* Datafile
Datafile.title -u-* Datafile
Datafile.memo -l-* Datafile
Datafile.size -d-* Datafile
Datafile.uploadedAt -d-* Datafile


entity Category <<ENTITY>> #fe500a
entity Category.id <<NUMBER>> #ffe396
entity Category.alias <<TEXT>> #ffe396
entity Category.description <<TEXT>> #ffe396
Category.id --* Category
Category.alias --* Category
Category.description -r-* Category

entity Update <<ENTITY>> #fe500a
entity Update.hash <<NUMBER>> #ffe396
entity Update.message <<TEXT>> #ffe396
entity Update.updateAt <<TEXT>> #ffe396
Update.hash --* Update
Update.message --* Update
Update.updateAt --* Update


User "0,*"-u-"1,1" Role
Permission_Role "0,*"--"1,1" Role
Permission "1,1"---"0,*" Permission_Role
User "1,1"-d-"0,*" Access
Access "0,*"-d-"1,1" Dataset
Category "0,1"---"0,*" Category
Category "0,*"--"1,1" Dataset
Dataset "0,*"--"1,1" Datafile
Dataset "1,1"--"0,*" Update
Update "0,*"--"1,1" User



@enduml



</center>